Chore/replace rison with json
SciCatProject/catanie pull request #768
Opened 2021-04-28 09:45 UTC by nitrosx

## Description

Remove rison dependency

## Motivation

## Motivation

We wanted to removed the dependency from rison library. All the interested files have been changed to use JSON instead of rison. 

## Fixes:

* angular.json
* package-lock.json
* package.json
* src/app/datasets/anonymous-dashboard/anonymous-dashboard.component.ts
* src/app/datasets/dashboard/dashboard.component.ts
* src/app/jobs/jobs-dashboard/jobs-dashboard.component.ts
* src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.spec.ts
* src/app/logbooks/logbooks-dashboard/logbooks-dashboard.component.ts
* src/app/policies/policies-dashboard/policies-dashboard.component.spec.ts
* src/app/policies/policies-dashboard/policies-dashboard.component.ts
* src/app/proposals/proposal-dashboard/proposal-dashboard.component.ts
* src/app/publisheddata/publisheddata-dashboard/publisheddata-dashboard.component.ts
* src/app/samples/sample-dashboard/sample-dashboard.component.ts
* src/app/shared/modules/breadcrumb/breadcrumb.component.ts
* src/app/state-management/effects/logbooks.effects.ts

## Changes:

* removed dependency in package.json and angular.js
* migrated from rison encode/decode to JSON stringify/parse

## Tests included/Docs Updated?

- [x] Included for each change/fix?
- [x] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?

2021-04-28 11:46 UTC, henrikjohansson712 requested changes
Looks good! Just found two commented out lines that should be removed.

2021-04-28 11:46 UTC, henrikjohansson712 commented on src/app/datasets/anonymous-dashboard/anonymous-dashboard.component.ts
> +//import * as rison from "rison";
This commented out import should be removed.

2021-04-28 11:46 UTC, henrikjohansson712 commented on src/app/datasets/anonymous-dashboard/anonymous-dashboard.component.ts
> +          //map((args) => (args ? rison.decode<DatasetFilters>(args) : {}))
This commented out line should be removed.

2021-04-28 13:39 UTC, nitrosx commented on src/app/datasets/anonymous-dashboard/anonymous-dashboard.component.ts
> +          //map((args) => (args ? rison.decode<DatasetFilters>(args) : {}))
Done.

2021-04-29 07:08 UTC, henrikjohansson712 approved these changes
Looks great!

2021-04-29 07:08 UTC, merged