Dataset detail
SciCatProject/catanie pull request #771
Opened 2021-05-05 07:51 UTC by nguyenlinhlinh

## Description
This PR solves issue #762 and made some small changes to the ErrorPageComponent.
## Motivation
See issue #762 
## Fixes:
- View a private dataset without logging in.
   <img width="1426" alt="Screenshot 2021-05-05 at 09 43 05" src="https://user-images.githubusercontent.com/17545757/117110391-564c5c80-ad86-11eb-9f9b-7b07b97147c8.png">
- View public dataset while being logged in => return dataset details (was empty before)
- View private dataset that the user doesn't have access to.
![Screenshot 2021-05-05 at 09 47 10](https://user-images.githubusercontent.com/17545757/117110768-eee2dc80-ad86-11eb-9dcb-af25c3e3fa74.png)
- Invalid url redirects to /404
![Screenshot 2021-05-05 at 09 49 00](https://user-images.githubusercontent.com/17545757/117110929-2782b600-ad87-11eb-99da-46e3c4e5c5a5.png)
## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of catamel API?

2021-05-05 11:19 UTC, henrikjohansson712 requested changes
I like the look of the error pages, just a few remarks on the displayed text.

2021-05-05 11:19 UTC, henrikjohansson712 commented on src/app/app-routing/app-routing.module.ts
> +        data: { errorTitle: "404 Page not found" , message: "Sorry, the page you are trying to view doesn't exists"}
For consistency, either replace the "does not" with "doesn't" here or the other way around in the other places.

2021-05-05 11:19 UTC, henrikjohansson712 commented on src/app/datasets/anonymous-details-dashboard/anonymous-details-dashboard.component.html
> +    [message]="'The dataset you are trying to view is either does not exist or requires authentication.'"
The "is" should be removed.

2021-05-05 11:19 UTC, henrikjohansson712 commented on src/app/datasets/dataset-details-dashboard/dataset-details-dashboard.component.html
> +    [message]="'The dataset you are trying to view is either does not exist or you do not have permission to view it.'"
The "is" should be removed.

2021-05-05 11:32 UTC, nguyenlinhlinh commented
Thank you. I will make changes.

2021-05-10 06:06 UTC, henrikjohansson712 approved these changes

2021-05-10 06:07 UTC, merged