Luxon
SciCatProject/catanie pull request #773
Opened 2021-05-12 15:22 UTC by nguyenlinhlinh

## Description

Short description of the pull request

## Motivation

Background on use case, changes needed

## Fixes:

* Items added

## Changes:

* changes made

## Tests included/Docs Updated?

- [ ] Included for each change/fix?
- [ ] Passing? (Merge will not be approved unless this is checked) 
- [ ] Docs updated?
- [ ] New packages used/requires npm install? 
- [ ] Toggle added for new features?
- [ ] Requires update of catamel API?

2021-05-18 08:53 UTC, henrikjohansson712 commented on src/app/files/files-dashboard/files-dashboard.component.ts
> +      id: "dataFileList.createdAt", icon: "access_time", label: "Created at", format: "date medium", canSort: true,
The change from `"dataFilelist.time"` to `"dataFileList.createdAt"` causes the *Created At* column to be empty. Looks like all the fields like `"createdAt"` and `"updatedAt"` are removed before the data gets loaded into the table, both on the items in `dataFileList` and in the `origDatablock` itself. @stephan271 do you know why?

2021-05-18 08:57 UTC, stephan271 commented on src/app/files/files-dashboard/files-dashboard.component.ts
> +      id: "dataFileList.createdAt", icon: "access_time", label: "Created at", format: "date medium", canSort: true,
I think there is no createdAt field for the individual files. Why was it changed from time to createdAt ?

2021-05-18 09:02 UTC, henrikjohansson712 commented on src/app/files/files-dashboard/files-dashboard.component.ts
> +      id: "dataFileList.createdAt", icon: "access_time", label: "Created at", format: "date medium", canSort: true,
There is on the ESS ones at least:

```json
  {
    "id": "000ae0b6-bddc-4b19-a86d-f5e1a6a161b9",
    "size": 0,
    "ownerGroup": "ess",
    "accessGroups": [
      "ess",
      "odin",
      "loki",
      "nmx"
    ],
    "createdBy": "ingestor",
    "datasetId": "20.500.12269/1073nicos_00001073.hdf",
    "dataFileList": [
      {
        "path": "nicos_00001073.hdf",
        "size": 0,
        "time": "2019-11-26T12:46:51.000Z",
        "chk": "34782",
        "uid": "101",
        "gid": "101",
        "perm": "755",
        "createdAt": "2021-05-18T08:46:50.700Z"
      }
    ],
    "createdAt": "2019-11-26T12:47:01.479Z",
    "updatedAt": "2019-11-26T12:47:01.480Z"
  }
```
But this is what's loaded into the table:

```json
{
    "dataFileList": {
        "path": "nicos_00001073.hdf",
        "size": 0,
        "time": "2019-11-26T12:46:51.000Z",
        "chk": "34782",
        "uid": "101",
        "gid": "101",
        "perm": "755"
    },
    "ownerGroup": "ess",
    "datasetId": "20.500.12269/1073nicos_00001073.hdf",
    "id": "000ae0b6-bddc-4b19-a86d-f5e1a6a161b9",
    "uniqueId": 1
}
```

2021-05-18 09:09 UTC, henrikjohansson712 commented on src/app/files/files-dashboard/files-dashboard.component.ts
> +      id: "dataFileList.createdAt", icon: "access_time", label: "Created at", format: "date medium", canSort: true,
I think I know why now. The Datafile model extends the MongoQueryable model, which in turn extends the Ownable model. So the `createdAt` on the items in the `dataFileList` gets added automatically with the current datetime, so it shows up on queries but is not actually stored in the database. So this should be changed back to use the `time` field.

2021-05-18 09:11 UTC, henrikjohansson712 requested changes
The change from `dataFileList.time` to `dataFileList.createdAt` should be reverted. Other than that everything seems to work correctly.

2021-05-18 10:09 UTC, nguyenlinhlinh commented on src/app/files/files-dashboard/files-dashboard.component.ts
> +      id: "dataFileList.createdAt", icon: "access_time", label: "Created at", format: "date medium", canSort: true,
The reason I change to `createAt` was because we got empty Create At column since we don't have `time` field. I will revert it.

2021-05-19 07:39 UTC, henrikjohansson712 approved these changes

2021-05-19 07:40 UTC, merged